I, [2014-11-27T14:04:29.294507 #6416]  INFO -- Kitchen: -----> Starting Kitchen (v1.2.1)
I, [2014-11-27T14:04:33.156497 #6416]  INFO -- Kitchen: -----> Creating <default-centos66>...
E, [2014-11-27T14:10:36.174094 #6416] ERROR -- Kitchen: ------Exception-------
E, [2014-11-27T14:10:36.174594 #6416] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2014-11-27T14:10:36.175094 #6416] ERROR -- Kitchen: Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos'...
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: default-centos66_default_1417093520764_73239
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8880 (adapter 1)
    default: 443 => 8443 (adapter 1)
    default: 22 => 2200 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1]
E, [2014-11-27T14:10:36.175594 #6416] ERROR -- Kitchen: ---Nested Exception---
E, [2014-11-27T14:10:36.176095 #6416] ERROR -- Kitchen: Class: Kitchen::ShellOut::ShellCommandFailed
E, [2014-11-27T14:10:36.176095 #6416] ERROR -- Kitchen: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos'...
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: default-centos66_default_1417093520764_73239
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8880 (adapter 1)
    default: 443 => 8443 (adapter 1)
    default: 22 => 2200 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1
E, [2014-11-27T14:10:36.176595 #6416] ERROR -- Kitchen: ------Backtrace-------
E, [2014-11-27T14:10:36.176595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:70:in `rescue in run_command'
E, [2014-11-27T14:10:36.177095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:59:in `run_command'
E, [2014-11-27T14:10:36.177595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/base.rb:158:in `run_command'
E, [2014-11-27T14:10:36.177595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.15.0/lib/kitchen/driver/vagrant.rb:123:in `run'
E, [2014-11-27T14:10:36.178095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.15.0/lib/kitchen/driver/vagrant.rb:68:in `create'
E, [2014-11-27T14:10:36.178595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `public_send'
E, [2014-11-27T14:10:36.178595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `block in perform_action'
E, [2014-11-27T14:10:36.178595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:305:in `call'
E, [2014-11-27T14:10:36.179095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:305:in `block in synchronize_or_call'
E, [2014-11-27T14:10:36.179095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:303:in `synchronize'
E, [2014-11-27T14:10:36.179595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:303:in `synchronize_or_call'
E, [2014-11-27T14:10:36.180095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:283:in `block in action'
E, [2014-11-27T14:10:36.180095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
E, [2014-11-27T14:10:36.180595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:282:in `action'
E, [2014-11-27T14:10:36.180595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `perform_action'
E, [2014-11-27T14:10:36.181095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:252:in `create_action'
E, [2014-11-27T14:10:36.181095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:246:in `block in transition_to'
E, [2014-11-27T14:10:36.181595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:245:in `each'
E, [2014-11-27T14:10:36.181595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:245:in `transition_to'
E, [2014-11-27T14:10:36.182095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:108:in `create'
E, [2014-11-27T14:10:36.182095 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:109:in `public_send'
E, [2014-11-27T14:10:36.182595 #6416] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
E, [2014-11-27T14:10:36.183095 #6416] ERROR -- Kitchen: ----------------------
I, [2014-11-27T14:14:43.925555 #9200]  INFO -- Kitchen: -----> Starting Kitchen (v1.2.1)
I, [2014-11-27T14:14:44.614642 #9200]  INFO -- Kitchen: -----> Destroying <default-centos66>...
I, [2014-11-27T14:14:44.633145 #9200]  INFO -- Kitchen: -----> Kitchen is finished. (0m0.71s)
I, [2014-11-27T14:15:23.574089 #5048]  INFO -- Kitchen: -----> Starting Kitchen (v1.2.1)
I, [2014-11-27T14:15:24.349688 #5048]  INFO -- Kitchen: -----> Creating <default-centos66>...
E, [2014-11-27T14:21:16.379890 #5048] ERROR -- Kitchen: ------Exception-------
E, [2014-11-27T14:21:16.380390 #5048] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2014-11-27T14:21:16.380390 #5048] ERROR -- Kitchen: Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos'...
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: default-centos66_default_1417094149386_52204
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8880 (adapter 1)
    default: 443 => 8443 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1]
E, [2014-11-27T14:21:16.380890 #5048] ERROR -- Kitchen: ---Nested Exception---
E, [2014-11-27T14:21:16.380890 #5048] ERROR -- Kitchen: Class: Kitchen::ShellOut::ShellCommandFailed
E, [2014-11-27T14:21:16.381390 #5048] ERROR -- Kitchen: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos'...
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: default-centos66_default_1417094149386_52204
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8880 (adapter 1)
    default: 443 => 8443 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
---- End output of vagrant up --no-provision --provider=virtualbox ----
Ran vagrant up --no-provision --provider=virtualbox returned 1
E, [2014-11-27T14:21:16.381390 #5048] ERROR -- Kitchen: ------Backtrace-------
E, [2014-11-27T14:21:16.381390 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:70:in `rescue in run_command'
E, [2014-11-27T14:21:16.381890 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:59:in `run_command'
E, [2014-11-27T14:21:16.381890 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/base.rb:158:in `run_command'
E, [2014-11-27T14:21:16.381890 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.15.0/lib/kitchen/driver/vagrant.rb:123:in `run'
E, [2014-11-27T14:21:16.381890 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/kitchen-vagrant-0.15.0/lib/kitchen/driver/vagrant.rb:68:in `create'
E, [2014-11-27T14:21:16.382390 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `public_send'
E, [2014-11-27T14:21:16.382390 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `block in perform_action'
E, [2014-11-27T14:21:16.382390 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:305:in `call'
E, [2014-11-27T14:21:16.382390 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:305:in `block in synchronize_or_call'
E, [2014-11-27T14:21:16.382890 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:303:in `synchronize'
E, [2014-11-27T14:21:16.382890 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:303:in `synchronize_or_call'
E, [2014-11-27T14:21:16.382890 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:283:in `block in action'
E, [2014-11-27T14:21:16.383391 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
E, [2014-11-27T14:21:16.383391 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:282:in `action'
E, [2014-11-27T14:21:16.383391 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `perform_action'
E, [2014-11-27T14:21:16.383391 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:252:in `create_action'
E, [2014-11-27T14:21:16.383891 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:246:in `block in transition_to'
E, [2014-11-27T14:21:16.383891 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:245:in `each'
E, [2014-11-27T14:21:16.383891 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:245:in `transition_to'
E, [2014-11-27T14:21:16.383891 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:108:in `create'
E, [2014-11-27T14:21:16.384391 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:109:in `public_send'
E, [2014-11-27T14:21:16.384391 #5048] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
E, [2014-11-27T14:21:16.384391 #5048] ERROR -- Kitchen: ----------------------
